unbind r
bind r source-file ~/.tmux.conf # reload tmux config
set -g focus-events on

set-option -g prefix C-j
bind Space copy-mode

set-option -g renumber-windows on
set -g base-index 1 # window starts at index 1
set -g mouse on
set-option -g detach-on-destroy off

# pane navigation
bind left select-pane -L
bind down select-pane -D
bind up select-pane -U
bind right select-pane -R

bind b set -g status # toogle status bar

set -g mode-keys vi # keybinds similar to vim
set -g status-position bottom
set -g status-left ""
set -g window-status-current-style bold # bold selected window
# set -g status-style bg=default

set -g status-right '#(echo "#{pane_current_path}" | sed "s:$HOME:~:")'

# Transparent background
set -g status-style 'bg=default fg=white'

# Status bar content styling
set -g window-status-current-style 'fg=white bold'
set -g window-status-style 'fg=brightblack'

# Create/Open AI session
bind-key a new-session -A -s AI

bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
